DROP TABLE IF EXISTS CHALLENGES;
CREATE TABLE CHALLENGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ROUTINE_NAME VARCHAR(30),
    SET INT(10),
    COUNT INT(10),
    CHALLENGE_NAME VARCHAR(30)
) DEFAULT CHARSET=utf8;
commit;