DROP TABLE CHALLENGES;
CREATE TABLE CHALLENGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ROUTINE_NAME1 VARCHAR(30),
    ROUTINE_NAME2 VARCHAR(30),
    ROUTINE_NAME3 VARCHAR(30),
    ROUTINE_NAME4 VARCHAR(30),
    ROUTINE_NAME5 VARCHAR(30),
    CHALLENGE_NAME VARCHAR(30)
) DEFAULT CHARSET=utf8;

insert into CHALLENGES(ROUTINE_NAME1,ROUTINE_NAME2,ROUTINE_NAME3,ROUTINE_NAME4,ROUTINE_NAME5,CHALLENGE_NAME) values('자전거','스쿼트','플랭크','풀업','푸쉬업','최소한의 운동');
insert into CHALLENGES(ROUTINE_NAME1,ROUTINE_NAME2,ROUTINE_NAME3,ROUTINE_NAME4,ROUTINE_NAME5,CHALLENGE_NAME) values('피티점프','벤치 딥스','슈퍼맨','니 푸쉬업','플랭크','하루 20분 전신운동');
insert into CHALLENGES(ROUTINE_NAME1,ROUTINE_NAME2,ROUTINE_NAME3,ROUTINE_NAME4,ROUTINE_NAME5,CHALLENGE_NAME) values('스쿼트','마운틴클라이머','푸쉬업','슈퍼맨','플랭크','10분 타바타 챌린지');
insert into CHALLENGES(ROUTINE_NAME1,ROUTINE_NAME2,ROUTINE_NAME3,ROUTINE_NAME4,ROUTINE_NAME5,CHALLENGE_NAME) values('체스트 프레스','랫풀 다운','케이블 로우','숄더프레스','덤벨 바이셉 컬','상/하체 2분할 트레이닝');
insert into CHALLENGES(ROUTINE_NAME1,ROUTINE_NAME2,ROUTINE_NAME3,ROUTINE_NAME4,ROUTINE_NAME5,CHALLENGE_NAME) values('점핑잭','크런치','브이업','플랭크','사이드 플랭크','11자/식스팩 프로젝트');

select * from CHALLENGES;

commit;